networks:
  dev:
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - crawler
      - extractor
      - database
    networks:
      - dev
  crawler:
    build:
      context: ./crawler
    depends_on:
      - database
    networks:
      - dev
  extractor:
    build:
      context: ./extractor
    depends_on:
      - database
    networks:
      - dev
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: urls_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev